### ISSUE TITLE
Create a function "isExpression()" that checks if a given String is an expression and has equal # of ( and )

### ISSUE THREAD

**Issue by BRDLF** [BRDLF/Hyperskill_Kotlin_SmartCalculator#8]

**Comment by rdsol** [comment]
Hello,
I can do with below approach.
Step 1. Find equal # of ( and ).
Step 2. Apply regex to check whether input string is expression or not.

If you find above approach correct and suitable, Assign this task to me so I can contribute.

**Comment by BRDLF** [comment]
Hello! Thank you for your comment.
I'm sorry, I am new to using github, and had only intended to use this issue board to track internal progress, and wasn't aware that by using the 'good first issue' label, it would draw attention.

I'm afraid I've already completed the changes and merged them, but thank you so much for your time.
